sudo: required

services:
  - docker

language: node_js
node_js:
  - '6.9.2'

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_SERVER

install:
  - npm install

script:
  - npm run sync

